///|
pub extend Argument with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Argument with Eq::{not_equal, equal}

///|
pub extend ArgumentKind with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ArgumentKind with Eq::{not_equal, equal}

///|
pub extend BasicHeader with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend BasicHeader with Eq::{not_equal, equal}

///|
pub extend ConfirmUpdate with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ConfirmUpdate with Eq::{not_equal, equal}

///|
pub extend Content with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Content with Eq::{not_equal, equal}

///|
pub extend Decoder with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FieldValue with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend FieldValue with Eq::{not_equal, equal}

///|
pub extend Frame with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Frame with Eq::{not_equal, equal}

///|
pub extend FrameError with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Method with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Method with Eq::{not_equal, equal}

///|
pub extend MethodSpec with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend MethodSpec with Eq::{not_equal, equal}

///|
pub extend PublishDecision with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PublishDecision with Eq::{not_equal, equal}

///|
pub extend PublishOutcome with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PublishOutcome with Eq::{not_equal, equal}

///|
pub extend PublishToken with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend PublishToken with Eq::{not_equal, equal}

///|
pub extend SessionEvent with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SessionEvent with Eq::{not_equal, equal}
