"""Rebuild the wire schema from the bundled, BSD-licensed RabbitMQ XML."""
from pathlib import Path
import hashlib
import json
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
source = root / 'spec/amqp0-9-1.stripped.extended.xml'
xml = ET.fromstring(source.read_bytes())
domains = {d.attrib['name']: d.attrib['type'] for d in xml.findall('domain')}
kinds = {'bit': 'BitKind', 'octet': 'OctetKind', 'short': 'ShortKind',
         'long': 'LongKind', 'longlong': 'LongLongKind', 'shortstr': 'ShortStringKind',
         'longstr': 'LongStringKind', 'table': 'TableKind'}
records = []
for cls in xml.findall('class'):
    for method in cls.findall('method'):
        fields = []
        for f in method.findall('field'):
            t = f.attrib.get('type') or domains[f.attrib['domain']]
            fields.append((f.attrib['name'], t))
        records.append(dict(class_id=int(cls.attrib['index']), method_id=int(method.attrib['index']),
                            name=cls.attrib['name'] + '.' + method.attrib['name'], fields=fields,
                            carries_content=method.attrib.get('content') == '1'))
q = json.dumps
out = ['// Generated by tools/generate-schema.py. Do not edit by hand.',
       '// Schema derived from spec/amqp0-9-1.stripped.extended.xml.',
       '// BSD copyright, conditions and disclaimer: see THIRD_PARTY.md and the XML.',
       '///|', 'pub fn method_spec(class_id : Int, method_id : Int) -> MethodSpec? {',
       '  match (class_id, method_id) {']
for rec in records:
    fields = ', '.join('(' + q(n) + ', ' + kinds[t] + ')' for n, t in rec['fields'])
    out.append(f'    ({rec["class_id"]}, {rec["method_id"]}) => Some({{ class_id: {rec["class_id"]}, method_id: {rec["method_id"]}, name: {q(rec["name"])}, fields: [{fields}], carries_content: {str(rec["carries_content"]).lower()} }})')
out += ['    _ => None', '  }', '}', '///|',
        'pub fn method_spec_by_name(name : String) -> MethodSpec? {', '  match name {']
for rec in records:
    out.append(f'    {q(rec["name"])} => method_spec({rec["class_id"]}, {rec["method_id"]})')
out += ['    _ => None', '  }', '}', '///|', 'pub fn method_names() -> Array[String] {',
        '  [' + ', '.join(q(r['name']) for r in records) + ']', '}']
(root / 'schema_generated.mbt').write_text('\n'.join(out) + '\n', encoding='utf-8')
(root / 'spec/methods.json').write_text(json.dumps(records, indent=2) + '\n', encoding='utf-8')
print(f'{len(records)} method schemas, source SHA256 {hashlib.sha256(source.read_bytes()).hexdigest()}')
