"""Generate independent wire golden tests with Pika 1.3.2 (installed separately).

PYTHONPATH may point to an extracted wheel. The repository has no Pika runtime dependency.
Inputs are original test cases; expected bytes come from Pika, not our encoder.
"""
from pathlib import Path
from datetime import datetime, timezone
from decimal import Decimal
import hashlib
import json
import struct
import pika
from pika import data, frame, spec

if pika.__version__ != '1.3.2':
    raise SystemExit('This evidence generator requires Pika 1.3.2')
root = Path(__file__).resolve().parents[1]
records = json.loads((root / 'spec/methods.json').read_text(encoding='utf-8'))
def quote(s): return json.dumps(s, ensure_ascii=False)
def mbbytes(b): return 'b"' + ''.join(f'\\x{x:02x}' for x in b) + '"'
def fv(v):
    if v is None: return 'Void'
    if isinstance(v, bool): return f'Boolean({str(v).lower()})'
    if isinstance(v, str): return f'LongString({mbbytes(v.encode())})'
    if isinstance(v, bytes): return f'ByteArray({mbbytes(v)})'
    if isinstance(v, int):
        if -2**31 <= v < 2**31: return f'Signed32({v})'
        if 0 <= v < 2**63: return f'Signed64({v}L)'
        raise ValueError('Pika uses a different table integer dialect outside the shared range')
    if isinstance(v, Decimal):
        n = v.normalize(); scale = max(0, -n.as_tuple().exponent)
        return f'Decimal({scale}, {int(n * Decimal(10) ** scale)})'
    if isinstance(v, datetime): return f'Timestamp({int(v.timestamp())}UL)'
    if isinstance(v, list): return 'ArrayValue([' + ', '.join(map(fv, v)) + '])'
    if isinstance(v, dict): return 'TableValue(' + table(v) + ')'
    raise TypeError(type(v))
def table(d): return '[' + ', '.join(f'({quote(k)}, {fv(v)})' for k, v in d.items()) + ']'
shared = {'中文': '消息', 'binary': b'\x00\xff', 'yes': True, 'no': False, 'min': -2**31,
          'large': 2**50 + 1, 'decimal': Decimal('-12.34'), 'nothing': None,
          'array': [1, 'nested', None, {'x': False}], 'time': datetime(2024, 1, 1, tzinfo=timezone.utc)}
def argument(kind, index, variant):
    high = variant == 1
    if kind == 'bit':
        v = (index % 2 == variant % 2) if variant else False
        return v, f'Bit({str(v).lower()})'
    if kind in ('octet', 'short', 'long', 'longlong'):
        widths = {'octet': 8, 'short': 16, 'long': 32, 'longlong': 64}
        v = 2**widths[kind] - 1 if high else (0 if variant == 0 else 17 + index)
        names = {'octet': 'Octet', 'short': 'Short', 'long': 'Long', 'longlong': 'LongLong'}
        suffix = {'octet': '', 'short': '', 'long': 'U', 'longlong': 'UL'}[kind]
        return v, f'{names[kind]}({v}{suffix})'
    if kind == 'shortstr':
        v = '中' * 85 if high else ('' if variant == 0 else '\ufeff任务')
        return v, f'ShortString({quote(v)})'
    if kind == 'longstr':
        v = b'\x00\xffPLAIN\x00' if high else (b'' if variant == 0 else '中文'.encode())
        return v, f'LongString({mbbytes(v)})'
    if kind == 'table':
        v = shared if high else ({} if variant == 0 else {'a': [True, None]})
        return v, 'Table(' + table(v) + ')'
    raise ValueError(kind)

out = ['// Generated by tools/generate-pika-vectors.py using Pika 1.3.2.',
       '// Original inputs; independent expected bytes. See evidence/pika-vectors.json.']
vectors = []
for rec in records:
    out += ['///|', f'test "Pika method {rec["name"]}" {{']
    cls = spec.methods[rec['class_id'] * 65536 + rec['method_id']]
    channel = 0 if rec['class_id'] == 10 else 65535
    for variant in range(3):
        pairs = [argument(kind, i, variant) for i, (_, kind) in enumerate(rec['fields'])]
        encoded = frame.Method(channel, cls(*(v for v, _ in pairs))).marshal()
        args = ', '.join(m for _, m in pairs)
        out += ['  {', f'    let command = @amqp.Method::new({quote(rec["name"])}, [{args}])',
                f'    let wire = {mbbytes(encoded)}',
                f'    assert_eq(command.encode({channel}).encode(), wire)',
                '    let decoder = @amqp.Decoder::new()',
                '    let received = decoder.feed(wire)', '    decoder.finish()',
                '    assert_eq(@amqp.Method::decode(received[0]), command)', '  }']
        vectors.append({'kind': 'method', 'name': rec['name'], 'variant': variant, 'hex': encoded.hex()})
    out.append('}')

prop_names = ['content-type','content-encoding','headers','delivery-mode','priority','correlation-id',
              'reply-to','expiration','message-id','timestamp','type','user-id','app-id','cluster-id']
prop_values = ['application/json','utf-8',shared,2,0,'订单','reply','60000','id-1',2**63+1,'test','guest','app','']
out += ['///|', 'test "Pika Basic properties all flags and individual presence" {']
for case, selected in enumerate([[], *[[i] for i in range(14)], list(range(14))]):
    values = [v if i in selected else None for i, v in enumerate(prop_values)]
    properties = spec.BasicProperties(*values)
    encoded = frame.Header(1, 2**64 - 1, properties).marshal()
    args = []
    for i in selected:
        v = prop_values[i]
        val = ('Table(' + table(v) + ')') if i == 2 else (f'Octet({v})' if i in (3,4) else (f'LongLong({v}UL)' if i == 9 else f'ShortString({quote(v)})'))
        args.append(f'({quote(prop_names[i])}, {val})')
    out += ['  {', f'    let header : @amqp.BasicHeader = {{ body_size: 18446744073709551615UL, properties: [{", ".join(args)}] }}',
            f'    let wire = {mbbytes(encoded)}', '    assert_eq(header.encode(1).encode(), wire)',
            '    let decoder = @amqp.Decoder::new()',
            '    assert_eq(@amqp.BasicHeader::decode(decoder.feed(wire)[0]), header)', '    decoder.finish()', '  }']
    vectors.append({'kind': 'header', 'case': case, 'hex': encoded.hex()})
out.append('}')
out += ['///|', 'test "Pika shared field-table types independent bytes" {']
tables = [{}, shared, *[{k: v} for k, v in shared.items()]]
for case, value in enumerate(tables):
    pieces = []; data.encode_table(pieces, value); encoded = b''.join(pieces)
    out += ['  {', f'    let entries : Array[(String, @amqp.FieldValue)] = {table(value)}',
            f'    let wire = {mbbytes(encoded)}', '    assert_eq(@amqp.encode_table(entries), wire)',
            '    assert_eq(@amqp.decode_table(wire), entries)', '  }']
    vectors.append({'kind': 'table', 'case': case, 'hex': encoded.hex()})
out.append('}')
(root / 'pika_vectors_test.mbt').write_text('\n'.join(out) + '\n', encoding='utf-8')
evidence = {'generator': 'Pika ' + pika.__version__, 'methodCases': len(records)*3,
            'headerCases': 16, 'tableCases': len(tables), 'execution': 'generated; validation recorded separately',
            'fieldDialect': 'RabbitMQ tags; only shared Pika table types compared. Pika L/U and unsigned l semantics are excluded.',
            'specSha256': hashlib.sha256((root / 'spec/amqp0-9-1.stripped.extended.xml').read_bytes()).hexdigest(),
            'vectors': vectors}
(root / 'evidence/pika-vectors.json').write_text(json.dumps(evidence, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(f'Generated {len(vectors)} independent wire vectors with Pika {pika.__version__}')
