"""Run a separately built pinned Go library; only normalize AMQPLAIN field order."""
from pathlib import Path
import datetime,hashlib,json,os,subprocess,sys
repo=Path(__file__).resolve().parents[1]
def sha(data):return hashlib.sha256(data).hexdigest()
def canonical_table(hex_value):
    data=bytes.fromhex(hex_value);pos=0;fields={}
    while pos<len(data):
        start=pos;length=data[pos];pos+=1;key=data[pos:pos+length].decode('ascii');pos+=length
        assert data[pos]==83;pos+=1;length=int.from_bytes(data[pos:pos+4],'big');pos+=4+length
        assert pos<=len(data) and key not in fields
        fields[key]=data[start:pos]
    assert set(fields)=={'LOGIN','PASSWORD'}
    return b''.join(fields[key] for key in sorted(fields)).hex()
def literal(s):return json.dumps(s,ensure_ascii=False)
def byte_literal(hex_value):return 'b"'+''.join('\\x'+hex_value[i:i+2] for i in range(0,len(hex_value),2))+'"'
def generated(cases):
    lines=['// Generated by tools/generate-auth-vectors.py from a pinned native Go run.']
    for mechanism in ['PLAIN','AMQPLAIN','EXTERNAL','X-BINARY']:
        lines+=['','///|',f'test "native authentication response vectors {mechanism}" {{']
        for row in cases:
            c=row['candidate']
            if c['Mechanism']!=mechanism:continue
            if mechanism in ['PLAIN','AMQPLAIN']:a=f'Authentication::{mechanism.lower()}({literal(c["Username"])}, {literal(c["Password"])})'
            elif mechanism=='EXTERNAL':a='Authentication::external()'
            else:a=f'Authentication::custom("X-BINARY", {byte_literal(c["ResponseHex"])})'
            lines+=['  {',f'    let s = Session::with_authentication([{a}])',f'    assert_eq(auth_reply(s, b"{mechanism}").arguments[2], LongString({byte_literal(row["normalizedResponseHex"])}))','  }']
        lines+=['}']
    return '\n'.join(lines)+'\n'
path=repo/'evidence/auth-native-vectors.json'
if '--check' in sys.argv:
    stored=json.loads(path.read_text(encoding='utf-8'))
    # moon fmt changes whitespace; compare the raw generator result via moon fmt on
    # generation only, while this guard compares a stored generated-source digest.
    assert sha((repo/'auth_native_test.mbt').read_bytes())==stored['generatedSourceSha256']
    print(f"{len(stored['cases'])} stored native authentication vectors in four backend groups verified")
    sys.exit()
binary=Path(os.environ['AMQP_AUTH_REFERENCE'])
build=json.loads((repo/'evidence/auth-reference-build.json').read_text(encoding='utf-8'))
assert sha(binary.read_bytes())==build['binarySha256']
pairs=[('',''),('demo','test'),('中','密'),('e\u0301','é'),('I\u00adX','a\u00a0b'),('Ⅸ','４'),('ا','p'),('😀','𝟘'),('\u0001x','p\n\t'),('name x','p x'),('u'*1025,'p'),('u','p'*1025)]
candidates=[]
for mechanism in ['PLAIN','AMQPLAIN']:
    for u,p in pairs+([('a\0b','p'),('u','a\0b')] if mechanism=='AMQPLAIN' else []):candidates.append(dict(Mechanism=mechanism,Username=u,Password=p))
candidates+=[dict(Mechanism='EXTERNAL')]+[dict(Mechanism='X-BINARY',ResponseHex=x) for x in ['', '00ff0178','e4b8ade5af86']]
request=json.dumps(dict(Operation='response',Candidates=candidates),ensure_ascii=False)+'\n'
reply=subprocess.run([str(binary)],input=request.encode(),capture_output=True,check=True,timeout=20)
response=json.loads(reply.stdout);assert response['ok'] and len(response['value'])==len(candidates)
cases=[]
for candidate,value in zip(candidates,response['value']):
    assert value['mechanism']==candidate['Mechanism']
    cases.append(dict(candidate=candidate,nativeResponseHex=value['responseHex'],normalizedResponseHex=canonical_table(value['responseHex']) if value['mechanism']=='AMQPLAIN' else value['responseHex']))
output=repo/'auth_native_test.mbt';output.write_text(generated(cases),encoding='utf-8',newline='\n')
subprocess.run(['moon','fmt','auth_native_test.mbt'],cwd=repo,check=True)
report=dict(utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),commit=build['commit'],binarySha256=build['binarySha256'],cases=cases,scope='30 native initial responses; only AMQPLAIN table entry order is normalized. Unicode is not normalized. PLAIN delimiter rejection is a local validation difference and tested separately.',generatedSourceSha256=sha(output.read_bytes()))
path.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
print(f'Generated {len(cases)} native authentication vectors')
